name: dd5tools
description: Gestion de personnages pour Donjons & Dragons 5
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  sqflite: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Bookinsanity (Remake)
      fonts:
        - asset: fonts/Bookinsanity.otf
        - asset: fonts/Bookinsanity_Bold.otf
          weight: 700
        - asset: fonts/Bookinsanity_Italic.otf
          style: italic
        - asset: fonts/Bookinsanity_Bold_Italic.otf
          weight: 700
          style: italic
    - family: Mr Eaves Small Caps (Remake)
      fonts:
        - asset: fonts/Mr_Eaves_Small_Caps.otf

flutter_icons:
  ios: true
  android: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"
